# Generated by Django 6.0.2 on 2026-02-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='org_structure_api.department'),
        ),
    ]
