# Generated by Django 6.0.2 on 2026-02-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure_api', '0003_alter_department_name_alter_employee_department_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'parent_id')},
        ),
    ]
